apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: curator-controller
  name: curator-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      name: curator-controller
  template:
    metadata:
      labels:
        name: curator-controller
    spec:
      containers:
      - command:
        - ./cluster-curator-controller
        env:
        - name: IMAGE_TAG
          value: sha256:84968c2fa9d305be8ef3dbc8f0342e6e32629203ecc0a4ed7afb06159fe57fae
        image: quay.io/jpacker/clustercurator-job@sha256:84968c2fa9d305be8ef3dbc8f0342e6e32629203ecc0a4ed7afb06159fe57fae
        imagePullPolicy: Always
        name: curator-controller
      serviceAccountName: cluster-curator
