apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: curator-controller
  name: curator-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      name: curator-controller
  template:
    metadata:
      labels:
        name: curator-controller
    spec:
      containers:
      - command:
        - ./cluster-curator-controller
        env:
        - name: IMAGE_TAG
          value: sha256:b66b934da2d56e78bfda0650038056f64f6763f17fa746cad8d4972b7a8eee44
        image: quay.io/jpacker/clustercurator-job@sha256:b66b934da2d56e78bfda0650038056f64f6763f17fa746cad8d4972b7a8eee44
        imagePullPolicy: Always
        name: curator-controller
      serviceAccountName: cluster-curator
