---
apiVersion: v1
kind: Template
metadata:
  name: cloud-provider-rbac
objects:
- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    name: ${TEMPLATE_NAME}-ctv           # Should include Template name
    namespace: ${TEMPLATE_NAMESPACE}
  rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    resourceName: ["${TEMPLATE_NAME}"]        # Template name
    verbs: ["get"]
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    name: ${TEMPLATE_NAME}-ctv           # Should include Template name
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: ${TEMPLATE_NAME}-ctv         # Should include Template name
  subjects:
  - kind: Group
    name: system:serviceaccounts
    apiGroup: rbac.authorization.k8s.io
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: ${TEMPLATE_NAME}                    # Template name
    namespace: ${TEMPLATE_NAMESPACE}
  data:
    clusterDeployment: |-
      apiVersion: hive.openshift.io/v1
      kind: ClusterDeployment
      metadata:
        name: cluster-name
      spec:
        baseDomain: my-domain.com
        clusterName: cluster-name
        installAttemptsLimit: 1
        controlPlaneConfig:
          servingCertificates: {}
        installed: false
        platform:
          aws:
            credentialsSecretRef:
              name: cluster-name-creds
            region: us-east-1
        provisioning:
          installConfigSecretRef:
            name: cluster-name-install-config
          sshPrivateKeySecretRef:
            name: cluster-name-ssh-private-key
          imageSetRef:
            # Find releases at quay.io/openshift-release-dev/ocp-release
            name: img4.6.1-x86-64
        pullSecretRef:
          name: cluster-name-pull-secret
    machinePool: |-
      apiVersion: hive.openshift.io/v1
      kind: MachinePool
      metadata:
        name: cluster-name-worker
      spec:
        clusterDeploymentRef:
          name: cluster-name
        name: worker
        platform:
          aws:
            rootVolume:
              iops: 100
              size: 100
              type: gp2
            type: m5.xlarge
        replicas: 3
    managedCluster: |-
      apiVersion: cluster.open-cluster-management.io/v1
      kind: ManagedCluster
      metadata:
        labels:
          cloud: Amazon
          region: us-east-1
          name: cluster-name
          vendor: OpenShift
        name: cluster-name
      spec:
        hubAcceptsClient: true
    klusterletAddonConfig: |-
      apiVersion: agent.open-cluster-management.io/v1
      kind: KlusterletAddonConfig
      metadata:
        name: cluster-name
      spec:
        clusterName: cluster-name
        clusterNamespace: cluster-name
        clusterLabels:
          cloud: Amazon
          vendor: OpenShift
        applicationManager:
          enabled: true
        policyController:
          enabled: true
        searchCollector:
          enabled: true
        certPolicyController:
          enabled: true
        iamPolicyController:
          enabled: true
        version: 2.1.0
    installConfig: |-
      apiVersion: v1
      metadata:
        name: cluster-name-install-config
      baseDomain: my-domain.com
      controlPlane:
        hyperthreading: Enabled
        name: master
        replicas: 3
        platform:
          aws:
            rootVolume:
              iops: 4000
              size: 100
              type: io1
            type: m5.xlarge
      compute:
      - hyperthreading: Enabled
        name: worker
        replicas: 3
        platform:
          aws:
            rootVolume:
              iops: 2000
              size: 100
              type: io1
            type: m5.xlarge
      networking:
        clusterNetwork:
        - cidr: 10.128.0.0/14
          hostPrefix: 23
        machineCIDR: 10.0.0.0/16
        networkType: OpenShiftSDN
        serviceNetwork:
        - 172.30.0.0/16
      platform:
        aws:
          region: us-east-1
      pullSecret: "" # skip, hive will inject based on it's Cloud Provider Secret
      sshKey: ""     # skip, hive will inject based on it's Cloud Provider Secret
parameters:
- description: The name used for this configMap cluster template
  name: TEMPLATE_NAME
  required: true
- description: The namespace used to store the configMap cluster template
  name: TEMPLATE_NAMESPACE
  required: true