---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cloud-provider-child-create
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["secrets"]
  verbs: ["create","patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
# This cluster role binding allows anyone in the "manager" group to read secrets in any namespace.
kind: RoleBinding
metadata:
    name: cloud-provider-child-create
subjects:
- kind: ServiceAccount
  name: default
  namespace: CLUSTER_NAMESPACE    # Cluster namespace
roleRef:
  kind: ClusterRole
  name: cloud-provider-child-create
  apiGroup: rbac.authorization.k8s.io