apiVersion: v1
kind: ConfigMap
metadata:
  name: my-cluster
  namespace: my-cluster
  labels:
    open-cluster-management: curator
data:
  providerCredentialPath: default/aws4jnp
  prehook: |-
    - name: Service now App Update
      extra_vars:
        sn_severity: 1
        sn_priority: 1
        appName: prehook job
        target_clusters:
          - jnp
  posthook: |-
     - name: Service now App Update
      extra_vars:
        sn_severity: 2
        sn_priority: 2
        appName: posthook job
        target_clusters:
          - jnp
