apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: cluster-deploy
  #name: cluster-deploy
spec:
  params:
  - name: CLUSTER_NAME
    value: jnp-job
  - name: PROVIDER_CREDENTIAL_PATH
    value: default/aws4jnp
  pipelineSpec:
    params:
    - name: CLUSTER_NAME
    - name: PROVIDER_CREDENTIAL_PATH
    tasks:
    - name: generate-secrets
      taskSpec:
        params:
        - name: CLUSTER_NAME
        - name: PROVIDER_CREDENTIAL_PATH
        #results:
        #- name: success
        steps:
        - name: generate-secrets
          image: quay.io/jpacker/clustercurator-job:0.1
          script: |
            ls
            export CLUSTER_NAME=$(params.CLUSTER_NAME)
            export PROVIDER_CREDENTIAL_PATH=$(params.PROVIDER_CREDENTIAL_PATH)
            /build-secrets
      params:
      - name: CLUSTER_NAME
        value: jnp-job
      - name: PROVIDER_CREDENTIAL_PATH
        value: default/aws4jnp

